swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "En Marche - Simulation Pouvoir d'Achat"
tags:
- name: "simulation"
  description: "Simulation de pouvoir d'achat"
schemes:
- "https"
paths:
  /simulation:
    post:
      tags:
      - "simulation"
      summary: "Launch a new simulation"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/Simulation"
      responses:
        422:
          description: "Invalid input"
definitions:
  Simulation:
    type: "object"
    required:
    - "parent1"
    - "menage"
    properties:
      parent1:
        $ref: "#/definitions/Parent"
      parent2:
        $ref: "#/definitions/Parent"
      enfants:
        type: "integer"
        format: "int64"
        example: 2
      menage:
        $ref: "#/definitions/Menage"
  Parent:
        type: "object"
        required:
        - "age"
        - "salaire_de_base"
        - "categorie_salarie"
        properties:
          age:
            type: "integer"
            format: "int64"
            example: 40
          salaire_de_base:
            type: "integer"
            format: "int64"
            example: 30000
          categorie_salarie:
            type: "string"
            example: "prive_non_cadre"
            enum:
              - "prive_non_cadre"
              - "prive_cadre"
              - "public_titulaire_etat"
              - "public_titulaire_militaire"
              - "public_titulaire_territoriale"
              - "public_titulaire_hospitaliere"
              - "public_non_titulaire"
              - "non_pertinent"
          retraite_brute:
            type: "integer"
            format: "int64"
          chomage_brut:
            type: "integer"
            format: "int64"
          statut_marital:
            type: "integer"
            format: "int64"
            example: 1
          taux_incapacite:
            type: "number"
            format: "float"
  Menage:
        type: "object"
        required:
        - "cotisation_taxe_habitation"
        properties:
          loyer:
            type: "integer"
            format: "int64"
            example: 750
          cotisation_taxe_habitation:
            type: "integer"
            format: "int64"
            example: 2562
          statut_occupation_logement:
            type: "integer"
            format: "int64"
            example: 3
            minimum: 1
            maximum: 7
          zone_apl:
            type: "integer"
            format: "int64"
            example: 1
            minimum: 1
            maximum: 3
